scss_files:
  - 'scss/**/*.scss'

linters:
  BorderZero:
    enabled: true
    convention: none
  ChainedClasses:
    enabled: true
  Comment:
    enabled: true
    allowed: '^/\*{2}'
  IdSelector:
    enabled: false
  Indentation:
    enabled: true
    character: tab
    width: 1
  PlaceholderInExtend:
    enabled: true
  PropertySortOrder:
    enabled: true
    order: concentric
  PropertyUnits:
    enabled: true
    global: ['px', 'em', 'rem', '%']
  LeadingZero:
    enabled: true
    style: include_zero
  TrailingZero:
    enabled: true
