pull_request_title: Translations updates from Crowdin
pull_request_labels: [enhancement, translations]
commit_message: 'New %language% translation for %file_name%%file_extension%'
append_commit_message: false
files:
  - source: /language/en/**/*.php
    translation: /language/%two_letters_code%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        es-ES: es
        es-MX: es_x_tu
        pt-BR: pt_br
