imports:
    - { resource: services_imgur.yml }

services:
    alfredoramos.imgur.listener:
        class: alfredoramos\imgur\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@routing.helper'
        tags:
            - { name: event.listener }

    alfredoramos.imgur.helper:
        class: alfredoramos\imgur\includes\helper
        arguments:
            - '@language'

    alfredoramos.imgur.controller:
        class: alfredoramos\imgur\controller\imgur
        arguments:
            - '@auth'
            - '@config'
            - '@template'
            - '@request'
            - '@controller.helper'
            - '@filesystem'
            - '@language'
            - '@user'
            - '@log'
            - '@alfredoramos.imgur.j0k3r.imgur.client'

    alfredoramos.imgur.acp.controller:
        class: alfredoramos\imgur\controller\acp
        arguments:
            - '@config'
            - '@template'
            - '@request'
            - '@language'
            - '@user'
            - '@log'
            - '@alfredoramos.imgur.j0k3r.imgur.client'
            - '@alfredoramos.imgur.helper'
