imports:
    - { resource: services_imgur.yml }

services:
    alfredoramos.imgur.listener:
        class: alfredoramos\imgur\event\listener
        tags:
            - { name: event.listener }

    alfredoramos.imgur.controller:
        class: alfredoramos\imgur\controller\imgur
        arguments:
            - '@config'
            - '@request'
            - '@controller.helper'
            - '@j0k3r.imgur.client'
